---
- name: Update seeds in config.toml file
  lineinfile:
    path: '{{ user_dir }}/{{ folder }}/config/config.toml'
    regexp: '^seeds ='
    line: 'seeds = "{{ seeds }}"'
    state: present
  when: seeds is defined

- name: Open prometheus port
  become: true
  ufw:
    rule: allow
    proto: tcp
    port: "{{ custom_port_prefix }}60"
  when:
    - node_exporter|bool == true

- name: Open p2p port
  become: true
  ufw:
    rule: allow
    proto: tcp
    port: "{{ custom_port_prefix }}56"

- name: Open rpc port
  become: true
  ufw:
    rule: allow
    port: "{{ custom_port_prefix }}57"
  when: type is defined and type != 'main'

- name: Create cosmovisor directories
  file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  with_items:
    - '{{ user_dir }}/{{ folder }}/cosmovisor/genesis/bin'
    - '{{ user_dir }}/{{ folder }}/cosmovisor/upgrades'

- name: copy daemon file to cosmovisor
  copy:
    src: '{{ user_dir }}/go/bin/{{ daemon }}'
    dest: '{{ user_dir }}/{{ folder }}/cosmovisor/genesis/bin'
    remote_src: true
    mode: '0755'

- name: copy service file
  become: true
  template:
    src: 'cosmovisor.service.j2'
    dest: '/etc/systemd/system/{{ daemon }}.service'
    owner: root
    group: root
    mode: '0644'

- name: start cosmovisor service
  become: true
  systemd:
    name: '{{ daemon }}'
    state: restarted
    daemon_reload: yes
    enabled: yes
